- id: 'bs_sage'
  aliases:
    - 'mrp'
    - 'rp'
    - 'beerp'
    - 'roleplay'
    - 'sage'
  name: 'BeeStation Sage'
  nickname: 'Sage'
  host: 'sage.beestation13.com'
  port: 7878
  open: true
  color: '0, 0, 150'
  rules_url: 'https://wiki.beestation13.com/view/Rules'

- id: 'bs_acacia'
  aliases:
    - 'overflow'
    - 'acacia'
  name: 'BeeStation Acacia'
  nickname: 'Acacia'
  host: 'acacia.beestation13.com'
  port: 7979
  open: true
  color: '0, 150, 0'
  rules_url: 'https://wiki.beestation13.com/view/Rules'

- id: 'bs_linden'
  aliases:
    - 'linden'
  name: 'BeeStation Linden'
  nickname: 'Linden'
  host: 'linden.beestation13.com'
  port: 7676
  open: false
  color: '0, 150, 0'
  rules_url: 'https://wiki.beestation13.com/view/Rules'
