version: '3'

services: 
  web:
    container_name: website
    image: crossedfall/beesite # For testing
    volumes:
      - ./config/site-settings:/beesite/app/config:ro
    networks:
      main:
        aliases:
          - web
    
  nginx:
    container_name: reverse-proxy
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - web:web
    depends_on: 
      - web
    networks:
      main:
        aliases:
          - nginx

networks:
  main:
