version: '3'

services: 
  web:
    build: .
    volumes: 
      - ./src:/beesite:ro
    environment:
      DEBUG: 'True'
    networks:
      main:
        aliases:
          - web
    
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./server-conf/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - web:web
    depends_on: 
      - web
    networks:
      main:
        aliases:
          - nginx

networks:
  main:
