version: '3'

services: 
  web:
    build: .
    volumes: 
      - ./src:/beesite:ro
    environment:
      DEBUG: 'True'
      APM: 'False' #Set to True to enable APM logging
      APM_URL: 'http://0.0.0.0:8200'
      APM_DEBUG: 'True'
      APM_TOKEN: '' #Leave empty if you aren't using a token
    networks:
      main:
        aliases:
          - web
    
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./server-conf/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - web:web
    depends_on: 
      - web
    networks:
      main:
        aliases:
          - nginx

networks:
  main:
