version: '3'

services:
  web:
    container_name: WOD13_website_app
    image: WOD13/WOD13
    ports:
      - "8080:8080"
    volumes:
      - ./config/site-settings:/app/WOD13/config:ro
    environment:
      APM: 'False' #Set to True to enable APM logging
      APM_URL: 'http://0.0.0.0:8200'
      APM_DEBUG: 'False'
      APM_TOKEN: '' #Leave empty if you aren't using a token
      UWSGI_USER: 'www-data'
      UWSGI_GROUP: 'www-data'
      UWSGI_THREADS: 10
      UWSGI_PROCESSES: 2
      UWSGI_OFFLOAD_THREADS: 10
