version: '3'

services: 
  web:
    image: crossedfall/beesite # For testing
    volumes:
      - ./config:/beesite/app/config:ro
    networks:
      main:
        aliases:
          - web
    
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./server-conf/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - web:web
    depends_on: 
      - web
    networks:
      main:
        aliases:
          - nginx

networks:
  main:
