database:
  game:
    host: '192.168.0.75'
    port: 3306
    user: 'root'
    pass: 'passwd'
    db: 'bee'
  site:
    host: '192.168.0.75'
    port: 3306
    user: 'root'
    pass: 'passwd'
    db: 'beesite'

patreon:
  client_id: 'xxx'
  client_secret: 'xxx'
  access_token: 'xxx'
  refresh_token: 'xxx'

api_passwd: 'changeme'
