static-url-path: "/static"

description: "BeeStation is a newbie friendly Space Station 13 server. The server was created in march 2018. We like to put a fun touch to the rounds to make a better experience."

api-base-url: "http://192.168.1.110:8081/"

links:
  discord: "https://discord.gg/Y7RTtkK"
  github: "https://github.com/BeeStation/BeeStation-Hornet"
  subreddit: "https://www.reddit.com/r/SS13"
  patreon: "https://www.patreon.com/beestation13"
  ss13-website: "https://spacestation13.com/"
  wiki: "https://wiki.beestation13.com"
  starter-guide: "https://wiki.beestation13.com/view/Starter_guide"

patreon:
  client-id: "test"